# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  demo-app:
#    image: alsenpaiii/demo-spring-layer:2.0
    build:
      dockerfile: demo.app_layer.Dockerfile
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
    ports:
      - 8082:8082
    volumes:
      - ~/app/:/app/
      - type: volume
        source: my-volume
        read_only: false
        target: /app
    networks:
      my_network:
        ipv4_address: 10.30.5.2
#    depends_on:
#      - nginx-app
#      - redis-app
  nginx-app:
    image: alsenpaiii/nginx:1.0
    container_name: nginx_container
    ports:
      - '80:80'
    networks:
      my_network:
        ipv4_address: 10.30.5.3
networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '10.30.0.0/16'
volumes:
  my-volume:
    driver: local
