## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
server:
  port: 8082

management:
  health:
    elasticsearch:
      enabled: false
#  endpoints:
#    web:
#      base-path: /management
#      exposure:
#        include: prometheus
#  prometheus:
#    metrics:
#      export:
#        enabled: true
#        step: 60

spring:
  application:
    name: DemoSpring
  elasticsearch:
    uris:  http://localhost:9200
    socket-timeout: 10s
  data:
    redis:
      host: redis-app

jhipster:
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:5173'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000