## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
server:
  port: 8082

management:
  health:
    elasticsearch:
      enabled: false

spring:
#  elasticsearch:
#    uris:  https://my-deployment-6b82ea.es.asia-east1.gcp.elastic-cloud.com
#    username: elastic
#    password: ANe0hhyfMCUlgh7EOV90Su5T
#    socket-timeout: 10s

jhipster:
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:5173'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000