## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
server:
  port: 8082


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=QLBanHang;integratedSecurity=true
    username: sa
    password: 123456
  liquibase:
    contexts: dev
  jpa:
    show-sql: true
    database: SQL_SERVER
    generate-ddl: false
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
#      hibernate.generate_statistics: false
#      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: false
#      hibernate.jdbc.batch_size: 25
#      hibernate.order_inserts: true
#      hibernate.order_updates: true
      # modify fetch size as necessary
#      hibernate.jdbc.fetch_size: 150
      hibernate.criteria.literal_handling_mode: BIND
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
#      hibernate.format_sql: true
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    open-in-view: false
## ==============JPA / HIBERNATE=================


# turn of auto initialize by lazy initialize
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true



#logging.pattern.console=
##================config web======================
#management.endpoints.web.cors.allowed-origins=*
#management.endpoints.web.cors.allowed-headers=GET,POST
