version: '3.8'
services:
  petrang-app:
    image: alsenpaiii/petrangapp:latest
    container_name: petrangcontainer
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://192.168.1.64:1433;database=QLBanHang
      - SPRING_LIQUIBASE_URL=jdbc:sqlserver://192.168.1.64:1433;database=QLBanHang
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=123456
    ports:
      - 8084:8082
