version: '3.8'
services:
  petrang-app:
    image: alsenpaiii/petrangapp:latest
    container_name: petrangcontainer
    volumes:
      - ~/log/:/tmp/
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://10.11.0.2:1433;database=QLBanHang
      - SPRING_LIQUIBASE_URL=jdbc:sqlserver://10.11.0.2:1433;database=QLBanHang
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=r00t.R00T
    networks:
      petrang-network:
        ipv4_address: 10.11.0.3
    ports:
      - 127.0.0.1:8080:8082
  petrang-mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
#     volumes are not supported on macOS
    volumes:
       - ~/database/:/var/opt/mssql/data/
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=r00t.R00T
      - MSSQL_DATABASE=QLBanHang
      - MSSQL_SLEEP=60
    # If you want to expose these ports outside your dev PC,
    # config ip
    networks:
      petrang-network:
          ipv4_address: 10.11.0.2
    ports:
      - 8081:1433
    command: /bin/bash -c '/opt/mssql/bin/sqlservr & echo "wait $$MSSQL_SLEEP sec for DB to start "; sleep $$MSSQL_SLEEP; /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -d tempdb -q "EXIT(CREATE DATABASE $$MSSQL_DATABASE)"; wait;'
networks:
  petrang-network:
    name: petrang-networking
  host-network:
    name: host
